#!/usr/bin/env node

var unparse = require('./index');

// Allows the server to be launched from another directory
process.chdir(__dirname);

// Get argv
var argv = process.argv;
if (argv[0] == 'node') {
	argv = argv.slice(2);
} else {
	argv = argv.slice(1);
}

// Parse argv
var opt = require('node-getopt').create([
	['h' , 'help', 'display this help']
])
.setHelp('Usage: node unparse [OPTIONS]\n'+
	'An open-source clone of Parse.\n\n'+
	'Arguments:\n'+
	'  server  start the server\n'+
	'  init  populate the database with default classes\n\n'+
	'Options:\n[[OPTIONS]]\n')
.bindHelp()
.parseSystem();

switch (opt.argv[0]) {
	case 'init':
		// Initialize unparse
		unparse.init().then(function () {
			process.exit(0);
		}, function (err) {
			console.error(err.stack || err);
			process.exit(1);
		});
		return;
	case 'server':
	default:
		// Start the server
		unparse.server();
}